### ISSUE TITLE
Je lijkt geen headings te gebruiken in je articles

### ISSUE THREAD

**Issue by Patrickkhr** [Vikkeyeftimov/connect-your-tribe-profile-card#10]
<img width="1304" alt="image" src="https://github.com/Vikkeyeftimov/connect-your-tribe-profile-card/assets/143999685/454f157c-b2f4-4e4c-8d9a-ce3ee4f6df50">

Je gebruikt geen headings in je article

Probeer een heading toe te voegen aan je articles dit is beter voor de toegankelijkheid.

Voor meer informatie: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article

**Comment by Vikkeyeftimov** [comment]
Ik heb je meer informatie doorgenomen en verbeterd. 

Er zit nu Headings in mijn codering (
````html
  <h1>Viktor Eftimov</h1>
  <h2>profile card</h2>
````
)

bedankt voor de issue
