### ISSUE TITLE
Duplicated ID

### ISSUE THREAD

**Issue by Daan645** [Vikkeyeftimov/connect-your-tribe-profile-card#2]
https://github.com/Vikkeyeftimov/connect-your-tribe-profile-card/blob/7c6984744bbbf7c1d7dbc2012b87f89e921db915/views/index.ejs#L72

In je code gebruik je meerdere keren het ID:  `return-back-redo-arrow` .

Je kunt hier een class van maken of verschillende ID. Een ID hoort namelijk uniek te zijn, als je meerdere elementen de zelfde styling wilt laten gebruiken kun je beter een class gebruiken.

Hier kun je meeer lezen over het verschil en gebruik van ids en classes:https://www.bestcolleges.com/bootcamps/guides/css-class-vs-id/#:~:text=You%20should%20use%20a%20class,They%20are%20not%20unique.

**Comment by Vikkeyeftimov** [comment]
Ik heb dit svg van internet gepakt dus wist niet dat het zo fout zal zijn maar heb ik nu gefixed om de hele id weg te halen had het toch niet nodig 
````html
  <button class="back-button"><?xml version="1.0" ?><svg style="enable-background:new 0 0 15.207 10.854;" version="1.1" viewBox="0 0 15.207 10.854" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M11.707,0h-4v1h4c1.378,0,2.5,1.122,2.5,2.5S13.085,6,11.707,6H1.914l3.146-3.146L4.354,2.146L0,6.5l4.354,4.354  l0.707-0.707L1.914,7h9.793c1.93,0,3.5-1.57,3.5-3.5S13.637,0,11.707,0z"/></svg>
  Terug</button>
````
