### ISSUE TITLE
Geen heading element in je article

### ISSUE THREAD

**Issue by lemuelmgsn** [Vikkeyeftimov/connect-your-tribe-profile-card#7]
https://github.com/Vikkeyeftimov/connect-your-tribe-profile-card/blob/7c6984744bbbf7c1d7dbc2012b87f89e921db915/views/index.ejs#L3-L7

Je hebt hier geen heading staan in je article wat wel nodig is.

Oplossing:
de article een heading geven of een div ervan maken als je geen heading wilt.

**Comment by Vikkeyeftimov** [comment]
````html
<h1>profile card</h1>
````
hier is mijn toegevoegde heading nu zal de probleem zijn opgelost 

bedankt voor de tip
