### ISSUE TITLE
schrijf je code in 1 taal

### ISSUE THREAD

**Issue by lemuelmgsn** [Vikkeyeftimov/connect-your-tribe-profile-card#8]
https://github.com/Vikkeyeftimov/connect-your-tribe-profile-card/blob/7c6984744bbbf7c1d7dbc2012b87f89e921db915/views/index.ejs#L16

https://github.com/Vikkeyeftimov/connect-your-tribe-profile-card/blob/7c6984744bbbf7c1d7dbc2012b87f89e921db915/views/index.ejs#L26

https://github.com/Vikkeyeftimov/connect-your-tribe-profile-card/blob/7c6984744bbbf7c1d7dbc2012b87f89e921db915/views/index.ejs#L3

https://github.com/Vikkeyeftimov/connect-your-tribe-profile-card/blob/7c6984744bbbf7c1d7dbc2012b87f89e921db915/views/index.ejs#L7

Probeer je class names en comments in 1 taal te schrijven. Dit is wat netter en maakt het in de toekomst makkelijker als je met andere mensen werkt die bijv. geen nederlands kunnen.

**Comment by Vikkeyeftimov** [comment]
Top bedankt voor de tip

heb het het allemaal verbeterd 
````html
<article class="articel">
````
https://github.com/Vikkeyeftimov/connect-your-tribe-profile-card/blob/main/views/index.ejs 
Dit link kan je alle verandering bekijken
